// FILE: src/theme/brand.ts
// Single source of truth for brand + UI copy. All shipped strings live here.

const BRAND = {
  appName: 'JobMesh',
  tagline: 'Tech jobs in India — without the fluff',
  fullName: 'JobMesh',
  description: 'Fresh tech jobs scraped daily from top Indian companies. Direct apply links, no middlemen.',
  twitter: '',
  contact: '/legal',
} as const;

const BRAND_SPLIT = { first: 'Job', accent: 'Mesh' } as const;

const SKETCH_FONT = "'Source Serif 4', 'Iowan Old Style', Georgia, ui-serif, serif";

const PALETTE = {
  primary: '#2D6A4F',
  primarySoft: 'rgba(45,106,79,0.10)',
  success: '#0F7B5A',
  danger: '#C5380F',
  warning: '#B66B0A',
  info: '#0A6CC7',
} as const;

const COPY = {
  nav: {
    today: 'Today',
    companies: 'Companies',
    browseJobs: 'Jobs',
    myProgress: 'Progress',
    hiring: 'Hiring',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
  },
  home: {
    heroLabel: 'Tech jobs in India — without the fluff',
    heroTitle1: 'Find your next',
    heroTitle2: 'tech role in India',
    heroSubtitle: 'We scrape top Indian tech companies daily. Fresh roles, direct apply links, no middlemen.',
    heroCTA: 'Browse jobs',
    heroSecondaryCTA: 'View companies',
    stat1Value: '50+',
    stat1Label: 'Companies',
    stat2Value: 'Daily',
    stat2Label: 'Fresh scrapes',
    companiesSectionLabel: 'Hiring now',
    companiesSectionTitle1: 'Top companies in',
    companiesSectionTitle2: 'India',
    scrollLeft: 'Scroll left',
    scrollRight: 'Scroll right',
    fullDirectory: 'Full directory',
    jobsSectionLabel: 'Fresh picks',
    jobsSectionTitle: 'Latest opportunities',
    viewAll: 'View all',
    loadMore: 'Load more',
  },
  jobs: {
    pageLabel: 'Opportunities',
    pageTitle: 'All tech jobs',
    rolesAvailable: 'roles available',
    noJobsTitle: 'No jobs found',
    noJobsBody: 'Try a different company or view all roles.',
    noEntryJobsBody: 'No entry-level roles found. Try turning off the fresher filter.',
    clearFilters: 'Clear filters',
    allJobs: 'All jobs',
    allCompanies: 'All companies',
    experienceLabel: 'Experience',
    companiesLabel: 'Companies',
    entryLevel: 'Entry level / Fresher',
    allLevels: 'All experience levels',
    applyNow: 'Apply now',
    readMore: 'Read more',
    showLess: 'Show less',
    postedPrefix: 'Posted',
    postedNA: 'No date',
    feedTitle: 'Job feed',
    rolesLabel: 'roles',
    filterLabel: 'Filter',
  },
  progress: {
    pageLabel: 'Tracking',
    pageTitle: 'My progress',
    backToJobs: 'Back to jobs',
    todayLabel: 'Today',
    noStreak: 'No streak yet',
    historyLabel: 'Recent applications',
    historySubtitle: 'Your latest applied jobs, useful for follow-ups and interview prep.',
    emptyTitle: 'No applications tracked yet',
    emptyBody: 'Start applying from the jobs feed and your recent history will appear here.',
  },
  directory: {
    pageLabel: 'Company directory',
    pageTitle1: 'Tech companies',
    pageTitle2: 'hiring in India',
    subtitle: 'Companies actively hiring across India — verified daily by our scraper.',
    searchPlaceholder: 'Search companies…',
    searchAriaLabel: 'Search companies',
    sortAriaLabel: 'Sort companies',
    noCompaniesTitle: 'No companies found',
    noCompaniesBody: 'Try a different search term or clear your filters.',
    sortAZ: 'A → Z',
    sortZA: 'Z → A',
    sortMostHiring: 'Most hiring',
    documentTitle: 'Tech companies hiring in India · JobMesh',
  },
  footer: {
    navigateTitle: 'Navigate',
    jobFeedLink: 'Job feed',
    companiesLink: 'Companies',
    legalTitle: 'Legal',
    legalInfoLink: 'Legal info',
    privacyLink: 'Privacy',
    contactLink: 'Contact',
    disclaimer: 'A non-commercial aggregator. Job details are scraped automatically — verify directly with employers.',
  },
  legal: {
    pageLabel: 'Legal',
    pageTitle: 'Legal information',
    lastUpdated: 'Last updated: March 2026',
    contactTitle: 'Contact',
    contactBody: 'For questions, data deletion requests, or legal enquiries, reach out at layer3studios.team@gmail.com.',
    sections: [],
  },
  site: {
    documentTitleJobs: 'Browse tech jobs in India · JobMesh',
    documentTitleProgress: 'My progress · JobMesh',
  },
  leaderboard: {
    pageLabel: 'Live leaderboard',
    pageTitle: "Who's actually hiring",
    pageTitleAccent: 'right now',
    shareButtonLabel: 'Share',
    shareTitle: "Who's actually hiring · JobMesh",
    loadingText: 'Loading leaderboard…',
    errorTitle: "Couldn't load the leaderboard",
    errorBody: 'Something went wrong. Try refreshing.',
    noMatchTitle: 'No companies match this filter',
    noMatchBody: 'Try a different filter or check back later.',
    summaryNewRoles: 'New roles this week',
    summaryTotalRoles: 'Total active roles',
    summaryHiringFast: 'Hiring fast',
    summaryPossiblyStale: 'Possibly stale',
    filterAll: 'All',
    sortNewThisWeek: 'New this week',
    sortTotalRoles: 'Total open roles',
    sortFreshest: 'Freshest listings',
    sortMostStale: 'Most stale',
    colNew: 'new',
    colTotal: 'total',
    colAge: 'avg age',
    colStale: 'stale',
    expandedWoW: 'Week over week:',
    expandedViewRoles: 'View open roles',
    showTop20: 'Show top 20',
    showAllPrefix: 'Show all',
    showAllSuffix: 'companies',
    methodologyTitle: 'How this works:',
    methodologyBody: 'We scrape job listings directly from company career pages (Greenhouse, Lever, Ashby, Workable, Workday, Recruitee, SmartRecruiters, Personio) every day. "New this week" = roles our scraper first saw in the last 7 days. "Possibly stale" = companies where 50%+ of listings are older than 30 days. Companies with only 1 listing are excluded.',
    documentTitle: "Who's actually hiring in India · JobMesh",
    subtitlePrefix: 'Updated',
    subtitleFrom: 'from',
    subtitleSuffix: 'companies actively posting tech roles in India.',
  },
} as const;

export { BRAND, BRAND_SPLIT, SKETCH_FONT, PALETTE, COPY };

export default { BRAND, BRAND_SPLIT, SKETCH_FONT, PALETTE, COPY };
